### ISSUE TITLE
Converrsion fails using Siemens dicom file 

### ISSUE THREAD

**Issue by behrouzvia** [wtclarke/spec2nii#125]
Hello, I'm facing an error while converting dicom files from Siemens scanner (Prisma_fit, VE11). It seems that the command expecting a software version indicated in the dicom header and it's missing. The error is pointing to "dicomfunctions.py", line 59, in xa_or_vx
 f' {img.dcm_data.SoftwareVersions} baseline scanner.'
 File "..../lib/python3.9/site-packages/pydicom/dataset.py", line 908, in __getattr__
 return object.__getattribute__(self, name)
AttributeError: 'FileDataset' object has no attribute 'SoftwareVersions'

Thanks in advance for any recommendations!
Best,
Behrouz

**Comment by behrouzvia** [comment]
I've tried converting by a raw .rda and Twix file as well and seeing the following errors. By the way, the data I'm trying to convert is an SVS using PRESS sequence. Any idea how to solve this issue? 

Command:  spec2nii raw MrSpec_Siemens.rda -n 1H
Error:
File ".../lib/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 2119: invalid start byte

Command: spec2nii twix MRS.dat -e EVALINFO  
Error: 
 File ".../lib/python3.9/site-packages/spec2nii/Siemens/twixfunctions.py", line 223, in process_svs
twixObj[dataKey].flagRemoveOS = remove_os
KeyError: 'EVALINFO'

**Comment by wtclarke** [comment]
Hi @behrouzvia,

Thanks for giving spec2nii a go. For the DICOM data, has the data been anonymised, or otherwise manipulated on or off the scanner?

The `.rda` pathway is much less tested than the others as I don't see much rda data. The other issue is that the encoding seems to be dependent on your locale, and the language settings.

The twix pathway should work if you give the right `EVALINFO` mask name. You can get these by running `spec2nii twix -v MRS.dat`. It is very likely to be `image`, so `spec2nii twix MRS.dat -e image`.

If you are able to share the data I am happy to take a deeper look.

**Comment by behrouzvia** [comment]
Hi @wtclarke , To answer your first question, no the DICOMs are not changed or anonymized. The full error description when using .rda file is as follows that looks angry about "other_formats.py" in readLCModelRaw. The twix file conversion now works, but I was looking to find some information about the size of the Voxel and its position that is not given in the JSON file. If you give me your email I can share the data with you, Thanks for your time. 

File "/Users/behrouz/miniconda3/envs/dev/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 696, in main
    spec2nii(*args)
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 292, in __init__
    args.func(args)
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 659, in raw
    self.imageOut, self.fileoutNames = lcm_raw(args)
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/site-packages/spec2nii/other_formats.py", line 73, in lcm_raw
    data, header = readLCModelRaw(args.file, conjugate=True)
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/site-packages/spec2nii/other_formats.py", line 153, in readLCModelRaw
    for line in f:
  File "/Users/behrouz/miniconda3/envs/dev/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 2119: invalid start byte

**Comment by behrouzvia** [comment]
> Ah, hold on, to convert .RDA you should use `spec2nii rda path/to/file.rda` not the `raw` sub command, that is for LCModel `.RAW` files.
> 
> My email is [william.clarke@ndcn.ox.ac.uk](mailto:william.clarke@ndcn.ox.ac.uk).
> 
> The size and position of the voxel is encoded in the affine matrix stored in the `sform` and `qform` headers of the generated nifti file. You can use `fslhd` or I think `spec2nii dump to inspect these.


@wtclarke, thank you very much! Sorry for my oversight. I,ve sent the files to your email. If I could get the geometry of the voxel by only converting the dicom, that would be great and I won't need to save the twix files.
So, using spec2nii dump I got following info which I think you are referring to. I think qoffset_x, y, and z are the voxel position but what about the voxel size? 

qoffset_x       : -0.826950507488
qoffset_y       : 58.2694011569
qoffset_z       : 19.0610286922
srow_x          : [20.         -0.         -0.         -0.82695051]
srow_y          : [ -0.         -19.99910558  -0.18914551  58.26940116]
srow_z          : [  0.           0.18914551 -19.99910558  19.06102869]

Also, the pixel dimension is given as follows which is not clear. 
pixdim          : [1.00e+00 2.00e+01 2.00e+01 2.00e+01 8.33e-04 1.00e+00 1.00e+00 1.00e+00]

Thank you again for the guidance!

**Comment by wtclarke** [comment]
In this case because there is no rotation of the voxel you can read the diagonals as the voxel size (20,20,20), which is also replicated in elements 2,3,4 of `pixdim` (element 1 has a special meaning, 5 is the dwell time and the others are default/unused). The position of the voxel is indeed the `qoffset_{x,y,z}` or the 4th column of the affine matrix. All values in mm.

Regarding the DICOM file you sent it's not a spectrocopy data file, or atleast it isn't reporting as one. It has an `SOPClassUID` of `1.2.840.10008.5.1.4.1.1.66` `Raw Data Storage`. Siemens MRS is identified by `1.3.12.2.1107.5.9.1` or `1.2.840.10008.5.1.4.1.1.4.2`. Please check you are using the right file, I'm not familiar with this `Raw Data Storage` format, but maybe it's something that a special reconstruction pipeline is producing.

**Comment by wtclarke** [comment]
Closing for now, but feel free to reopen if you can't get to the bottom of which DICOM to use
