### ISSUE TITLE
Issue to read DICOM MR Spectroscopy Storage (Philips and Siemens) 

### ISSUE THREAD

**Issue by manuegrx** [wtclarke/spec2nii#32]
Hi, 

Thank you for sharing your software. 

I have DICOM data from different MRI scanners and for two scanners (one Philips and one Siemens) spec2nii does not work. 
This is because the format is not the expected one.  The tag (0008, 0016) SOP Class UID  is "MR Spectroscopy Storage "  as for the data from Siemens system with the software version XA (here for the Siemens scanner the software version is syngo MR E11). 

The DICOM are quite similar as the one from XA software (for example the data are stored in the tag (5600, 0020) Spectroscopy Data ). However they are some differences for others tag in particular for the data from Philips system. 

Maybe it can be usefull to check the storage method in order to chose wich part of the code use to read the rawdata and not only the software version ? 
So far, here are the different  SOP Class UID I found :
-  DICOM specifc for spectroscopy for both Siemens and Philips systems :  '1.2.840.10008.5.1.4.1.1.4.2' (='MR Spectroscopy Storage')
-  classic DICOM for Philips systems : '1.3.46.670589.11.0.0.12.1'
- classic DICOM for Siemens systems : '1.3.12.2.1107.5.9.1' (= 'CSA Non-Image') 

I cannot share my data in open source but if you are interrested I can see if I can share them with you.    

Kind regards, 

Emmanuelle Gourieux

**Comment by wtclarke** [comment]
Hi Emmanuelle,

Thanks for giving spec2nii a go.

For the Phillips data did you try the dedicated command? `spec2nii philips_dcm DCM_FILE_or_DIR`

And are you saying that there is DICOM data generated by non XA scanners that conforms to the DICOM spectroscopy standard? I hadn't come across that before. Yes please, could you see if you can share the data by some private method?

**Comment by manuegrx** [comment]
Yes for Philips data I used the dedicated command but as it is not the same type of DICOM it does not work. 
Here is the issue: 
```
Traceback (most recent call last):
  File "/home/eg262050/miniconda3/envs/spec2nii/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 513, in main
    spec2nii(*args)
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 260, in __init__
    args.func(args)
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 459, in philips_dicom
    self.imageOut, self.fileoutNames = multi_file_dicom(files_in, args.fileout, args.tag, args.verbose)
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/philips_dcm.py", line 51, in multi_file_dicom
    specDataCmplx, spec_ref, orientation, dwelltime, meta_obj, meta_ref_obj = _process_philips_svs(img, verbose)
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/philips_dcm.py", line 165, in _process_philips_svs
    meta = _extractDicomMetadata(img)
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/spec2nii/philips_dcm.py", line 267, in _extractDicomMetadata
    rep_tim = float(dcmdata.dcm_data.PerFrameFunctionalGroupsSequence[0]
  File "/home/eg262050/miniconda3/envs/spec2nii/lib/python3.8/site-packages/pydicom/dataset.py", line 836, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Dataset' object has no attribute 'MRTimingAndRelatedParametersSequence'
```


And yes I have some  DICOM data generated by non XA scanners that conforms to the DICOM spectroscopy standard (from both Philips and Siemens systems). I will try to send you data this week !

**Comment by wtclarke** [comment]
Hi, I'm going to close this due to age and lack of activity. Feel free to reopen if required

**Comment by sofiasp96** [comment]
Hi, I hope it’s okay to reopen this discussion here; I’m facing a very similar error on Siemens syngo MR E11.

I'm new to MRS. I'm trying to convert some DICOM files to NIfTI and I'm facing the following issues.

Before explaining my issues, let me show you some information:

· Python version: 3.11.9
· OS: Linux
· spec2nii version: 0.8.7

· The data were acquired on a SIEMENS scanner. See below some DICOM tags:
--> Tag 0018 1020   ACQ Software Version//syngo MR E11

Some of my  DICOM files have:
--> Tag 0008 0016   ID SOP Class UID//1.2.840.10008.5.1.4.1.1.4
--> Tag 0008 0008   ID Image Type//DERIVED\PRIMARY\SPECTROSCOPY\REFERENCEIMAGE

And one DICOM file in the same folder has:
--> Tag 0008 0016   ID SOP Class UID//1.2.840.10008.5.1.4.1.1.7  (only one DICOM)
--> Tag 0008 0008   ID Image Type//DERIVED\PRIMARY\SPECTROSCOPY\SPECTRUM

**MY ISSUE:**

When I try to convert my DICOM using _spec2nii dicom -f . PATIENT123/dicom_file_ I get this:

/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/Siemens/dicomfunctions.py:10: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them
  import nibabel.nicom.dicomwrappers
Single file conversion.
Traceback (most recent call last):
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/bin/spec2nii", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/spec2nii.py", line 701, in main
    spec2nii(*args)
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/spec2nii.py", line 297, in __init__
    args.func(args)
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/spec2nii.py", line 547, in dicom
    self.imageOut, self.fileoutNames = multi_file_dicom(files_in, args.fileout, args.tag, args.verbose)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/Siemens/dicomfunctions.py", line 105, in multi_file_dicom
    raise exc
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/Siemens/dicomfunctions.py", line 102, in multi_file_dicom
    mrs_type = svs_or_CSI(img)
               ^^^^^^^^^^^^^^^
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/Siemens/dicomfunctions.py", line 65, in svs_or_CSI
    if xa_or_vx(img) == 'vx':
       ^^^^^^^^^^^^^
  File "/home/apps/packages/Anaconda/Anaconda3-2024.02-1/lib/python3.11/site-packages/spec2nii/Siemens/dicomfunctions.py", line 49, in xa_or_vx
    raise IncompatibleSOPClassUID(
spec2nii.Siemens.dicomfunctions.IncompatibleSOPClassUID: spec2nii detected SOPClassUID 1.2.840.10008.5.1.4.1.1.4. This normally contains MR imaging (not spectroscopy) data. This data was collected on a syngo MR E11 baseline scanner. spec2nii is tested on VA-VE, XA20, and XA30 DICOM files.

There are several errors, but what I guess is that the root cause is related with the incompatibility with the SOPClassUID. Is it possible that the main issue is because of the following function in dicomfunctions.py?:

def xa_or_vx(img):
    """Determine siemens DICOM type

    :param img: DICOM image object
    :type img: nibabel.nicom.dicomwrappers.SiemensWrapper
    :raises IncompatibleSOPClassUID: Raised if not a Siemens Syngo Non Image Storage or MRSpectroscopyStorage dicom file
    :return: String either 'xa' or 'vx'
    :rtype: str
    """
    **if img.dcm_data.SOPClassUID == '1.3.12.2.1107.5.9.1':
        return 'vx'
    elif img.dcm_data.SOPClassUID == '1.2.840.10008.5.1.4.1.1.4.2':
        return 'xa'
    else:
        if img.dcm_data.SOPClassUID == '1.2.840.10008.5.1.4.1.1.4':
            raise IncompatibleSOPClassUID(**
                f'spec2nii detected SOPClassUID {img.dcm_data.SOPClassUID}.'
                ' This normally contains MR imaging (not spectroscopy) data.'
                ' This data was collected on a'
                f' {img.dcm_data.SoftwareVersions} baseline scanner.'
                ' spec2nii is tested on VA-VE, XA20, and XA30 DICOM files.')
        else:
            raise IncompatibleSOPClassUID(
                'spec2nii does not recognise this SOPClassUID '
                f'{img.dcm_data.SOPClassUID} as MRS data. This data was collected on a'
                f' {img.dcm_data.SoftwareVersions} baseline scanner.'
                ' spec2nii is tested on VA-VE, XA20, and XA30 DICOM files.')


Is this behaviour expected for Siemens syngo MR E11 data where spectroscopy information seems to be stored with SOP Class UIDs 1.2.840.10008.5.1.4.1.1.4 and 1.2.840.10008.5.1.4.1.1.7?

Is there any recommended workaround, or is support for this type of E11 DICOM layout planned?

Thank you in advance. If required I could provide additional (anonymised) information if that helps.

Sofia.
